<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>464e54fe-65b9-42f2-8dc5-741c3b952abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq25GLF-Gg-_XL2HOT4Rbp3Q1lJPRRn0jLl874mS3wBxukp4gVVhJTpalC0wlxUTJ2-b48WGleGYc2ezouBA23couwnsiKZKqxP4WaG-06yiu0u0iozqCS7Ytz-wnJKe9M4ngKRmQ7Ncb2dTUqqnPkpq4RcAYmYPwk0i-0bHBxN1GLD3R09YUZNnolRl1Rll8s-pYNZ8tqCZ6NZuAad0OxjYow7SBeg&amp;k=6LdpEVIUAAAAAC7zQjhpuI6FCQW0dd5aWfjj20er</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/General/Page_Report Piracy/iframe_Accept_c-lwo4lb197h6c</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq25GLF-Gg-_XL2HOT4Rbp3Q1lJPRRn0jLl874mS3wBxukp4gVVhJTpalC0wlxUTJ2-b48WGleGYc2ezouBA23couwnsiKZKqxP4WaG-06yiu0u0iozqCS7Ytz-wnJKe9M4ngKRmQ7Ncb2dTUqqnPkpq4RcAYmYPwk0i-0bHBxN1GLD3R09YUZNnolRl1Rll8s-pYNZ8tqCZ6NZuAad0OxjYow7SBeg&amp;k=6LdpEVIUAAAAAC7zQjhpuI6FCQW0dd5aWfjj20er')])[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
